version: '3.4'
services:
  #mysql镜像
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "~/docker/mysql:/var/lib/mysql"
      # - type: volume
        # source: mysql-target
        # target: /var/lib/mysql

  #mssql镜像
  # mssql:
  #   image: microsoft/mssql-server-linux
  #   restart: always
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     ACCEPT_EULA: Y
  #     MSSQL_SA_PASSWORD: H123s456l78
  #   volumes:
  #     - type: volume
  #       source: /var/docker/mssql
  #       target: /var/opt/mssql
  #mongodb镜像
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "~/docker/mongo:/data/db"
      # - type: volume
        # source: mongo-target
        # target: /data/db

  #postgresql镜像
  # postgres:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #       POSTGRES_PASSWORD: 123456
  #   volumes:
  #       - type: volume
  #         source: /var/docker/postgres
  #         target: /var/lib/postgresql/data
  #jenkins 镜像  permission defined sudo chown -R 1000:1000 /var/docker/jenkins
  jenkins:
    image: jenkins
    restart: always
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - "~/docker/jenkins:/var/jenkins_home"
      # - type: volume
        # source: jenkins-target
        # target: /var/jenkins_home
  # redis镜像
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "~/docker/redis:/data"
      # - type: volume
        # source: redis-target
        # target: /data
  #oracle 镜像
  # oracle:
  #   image: sath89/oracle-12c
  #   restart: always
  #   ports:
  #     - "1521:1521"
  #   environment:
  #     MANUAL_DBCA: "true"
  #     PASS: 123456
  #     DBCA_TOTAL_MEMORY: 1024
  #   volumes:
  #     - type: volume
  #       source: /var/docker/oracle
  #       target: /u01/app/oracle

  #swagger-editor
  swagger-editor:
    image: swaggerapi/swagger-editor
    restart: always
    ports:
      - "8082:8080"

  #nexus私服  chown -R 200 /var/docker/nexus3
  nexus3:
    image: sonatype/nexus3
    restart: always
    ports:
      - "8083:8081"
    volumes:
      - "~/docker/nexus3:/nexus-data"
      # - type: volume
        # source: nexus3-target
        # target: /nexus-data
    environment:
      MAX_HEAP: 768m

  #grafana
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 123456
    volumes:
      - "~/docker/grafana:/var/lib/grafana"
      # - type: volume
        # source: grafana-target
        # target: /var/lib/grafana
    links:
      - prometheus

  #prometheus  chown -R  nobody  /var/docker/prometheus
  prometheus:
    image: quay.io/prometheus/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "~/docker/prometheus:/prometheus"
      #  type: volume
        # source: prometheus-target
        # target: /prometheus

 #gitlab
 #git clone ssh://git@git.hsulei.com:10022/myuser/awesome-project.git
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG:
        external_url 'http://gitlab.hsulei.com'
    ports:
      - "10443:443"
      - "80:80"
      - "10022:22"
    volumes:
      - "~/docker/gitlab/data:/var/opt/gitlab"
      - "~/docker/gitlab/logs:/var/log/gitlab"
      - "~/docker/gitlab/config:/etc/gitlab"
      # - type: volume
        # source: gitlab-data-target
        # target: /var/opt/gitlab
      # - type: volume
        # source: gitlab-log-target
        # target: /var/log/gitlab
      # - type: volume
        # source: gitlab-config-target
        # target: /etc/gitlab
